---
parserOptions:
  ecmaVersion: 6
env:
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parser: 
  "babel-eslint"
rules:
  prettier/prettier:
    - error
  no-underscore-dangle: off
  class-methods-use-this: off
      
