export default [
  {
    name: 'Controles de Características',
    header: ['Dificultad', 'Valor'],
    body: [
      ['simple', '6+'],
      ['normal', '10+'],
      ['complejo', '15+'],
      ['extremo', '20+'],
    ],
  },
  {
    name: 'Bonos de Características',
    header: ['Características', 'Bonos'],
    body: [
      ['1', '-30'],
      ['2', '-20'],
      ['3', '-10'],
      ['4', '-5'],
      ['5', '0'],
      ['6-7', '+5'],
      ['8-9', '+10'],
      ['10', '+15'],
      ['11-12', '+20'],
      ['13-14', '+25'],
      ['15', '+30'],
      ['16-17', '+35'],
      ['18-19', '+40'],
      ['20', '+45'],
    ],
  },
  {
    name: 'Tamaño y peso',
    header: ['Tamaño', 'Altura', 'Peso'],
    body: [
      ['2', '0.20 a 0.60 m', '5 a 15kg'],
      ['3', '0.40 a 0.60 m', '10 a 20 kg'],
      ['4', '0.60 a 1.00 m', '20 a 30 kg'],
      ['5', '0.80 a 1.20 m', '20 a 50 kg'],
      ['6', '1.00 a 1.40 m', '30 a 50 kg'],
      ['7', '1.10 a 1.50 m', '30 a 60 kg'],
      ['8', '1.20 a 1.60 m', '35 a 70 kg'],
      ['9', '1.30 a 1.60 m', '40 a 80 kg'],
      ['10', '1.40 a 1.70 m', '40 a 90 kg'],
      ['11', '1.40 a 1.80 m', '50 a 100 kg'],
      ['12', '1.50 a 1.80 m', '50 a 120 kg'],
      ['13', '1.50 a 1.80 m', '50 a 140 kg'],
      ['14', '1.60 a 1.90 m', '50 a 150 kg'],
      ['15', '1.60 a 2.00 m', '60 a 180 kg'],
      ['16', '1.70 a 2.10 m', '70 a 220 kg'],
      ['17', '1.70 a 2.10 m', '80 a 240 kg'],
      ['18', '1.80 a 2.20 m', '90 a 260 kg'],
      ['19', '1.90 a 2.30 m', '100 a 280 kg'],
      ['20', '2.00 a 2.40 m', '110 a 320 kg'],
      ['21', '2.10 a 2.60 m', '120 a 450 kg'],
      ['22', '+2.5 m', '+400 kg'],
    ],
  },
  {
    name: 'Puntos de Vida Base',
    header: [
      'Constitución',
      'Puntos de Vida Base',
    ],
    body: [
      ['1', '5'],
      ['2', '20'],
      ['3', '40'],
      ['4', '55'],
      ['5', '70'],
      ['6', '85'],
      ['7', '95'],
      ['8', '110'],
      ['9', '120'],
      ['10', '135'],
      ['11', '150'],
      ['23', '160'],
      ['13', '175'],
      ['14', '185'],
      ['15', '200'],
      ['16', '215'],
      ['17', '225'],
      ['18', '240'],
      ['19', '250'],
      ['20', '265'],
    ],
  },
  {
    name: 'Presencia Base',
    header: ['Nivel', 'Presencia'],
    body: [
      ['1', '30'],
      ['2', '35'],
      ['3', '40'],
      ['4', '45'],
      ['5', '50'],
      ['6', '55'],
      ['7', '60'],
      ['8', '65'],
      ['9', '70'],
      ['10', '75'],
      ['11', '80'],
      ['12', '85'],
      ['13', '90'],
      ['14', '95'],
      ['15', '100'],
      ['+1 nivel', '+5'],
    ],
  },
  {
    name: 'Progresión Por Nivel',
    header: [
      'Nivel',
      'PD',
      '+Características por nivel',
      'Experiencia Necesaria',
      'Presencia Base',
    ],
    body: [
      ['0', '400', '', 'N/A', '20'],
      ['1', '600', '', '0', '30'],
      ['2', '700', '+1', '100', '35'],
      ['3', '800', '', '225', '40'],
      ['4', '900', '+1', '375', '45'],
      ['5', '1000', '', '550', '50'],
      ['6', '1100', '+1', '750', '55'],
      ['7', '1200', '', '975', '60'],
      ['8', '1300', '+1', '1225', '65'],
      ['9', '1400', '', '1500', '70'],
      ['10', '1500', ' +1', '1800', '75'],
      ['11', '1600', '', '2125', '80'],
      ['12', '1700', ' +1', '2475', '85'],
      ['13', '1800', '', '2850', '90'],
      ['14', '1900', '+1', '3250', '95'],
      ['15', '2000', '', '3675', '100'],
      [
        '+1',
        '+100',
        '+1 (Cada nivel par)',
        '+450',
        '+5',
      ],
    ],
  },
  {
    name: 'Dificultades',
    header: [
      'Dificultad',
      'Requerimientos',
      'Explicación',
    ],
    body: [
      [
        'Rutinario RUT',
        '20',
        'Son acciones normales, que todos realizamos a la primera sin ni siquiera tener la necesidad de saber hacerlas, como bajar de un salto las escaleras o escuchar una explosión. Por regla general, el Director de Juego nunca pedirá a un jugador practicar controles de habilidad de esta dificultad, salvo en circunstancias muy determinadas.',
      ],
      [
        'Fácil FAC',
        '40',
        'Las acciones fáciles son cosas que todos estamos acostumbrados a realizar, como abrir una cerradura oxidada sin problemas o recordar un simple tarareo. Incluso si no se sabe nada de la materia, un par de intentos fallidos bastarán para conseguirlo finalmente. El problema es si tiene que salirte bien a la primera, y debes abrir esa puerta oxidada antes de que ellos te alcancen...',
      ],
      [
        'Media MED',
        '80',
        'Es un nivel de dificultad mayor. Son cosas que la mera suerte no siempre te permite hacer y sólo alguien que tenga conocimientos en la materia podrá realizar comúnmente, como forzar una cerradura simple o curar una molesta gripe.',
      ],
      [
        'Difícil DIF',
        '120',
        'Son aquellas acciones que resultan muy problemáticas para una persona normal. Requieren una gran dosis de habilidad o una suerte desigual para realizarlas. Son actividades complejas por naturaleza, como subir por una pared escarpada sin ayuda o realizar malabares circenses.',
      ],
      [
        'Muy difícil MDF',
        '140',
        'Para realizar acciones muy difíciles se requiere una enorme habilidad. Es el límite de dificultad que pueden alcanzar las personas normales. Sólo los mejores expertos podrán realizarlas sin problemas, y siempre dejando boquiabiertos a quienes les observen. Algunos ejemplos serían caminar por la cuerda floja o realizar un salto mortal en el trapecio.',
      ],
      [
        'Absurdo ABS',
        '180',
        'Como su nombre indica, son cosas que están más allá de las posibilidades de una persona normal. Únicamente los grandes campeones o los superdotados podrían llegar a realizarlas con habitualidad, aunque no sin cierto esfuerzo. Algunos ejemplos serían hacer acrobacias olímpicas en la pértiga o realizar operaciones matemáticas como una calculadora mecánica.',
      ],
      [
        'Casi imposible CIM',
        '240',
        'Incluso los mejores encontrarán mucha dificultad en estas acciones casi imposibles, y la mayoría de veces estarán condenadas al fracaso. Son actos que sólo un gran campeón o el héroe de la película consiguen en el momento crítico, como correr por un puente que se derrumba apoyándose en las piedras que están cayendo y realizar un increíble salto final.',
      ],
      [
        'Imposible IMP',
        '280',
        'Realizar una acción imposible es algo que nadie pensaría que se puede hacer. Son actos que bordean aquello que llamamos realidad pero que, por increíble o milagroso que parezca, son físicamente posibles. Un experto necesitará tener el momento más brillante de su carrera para conseguir algo imposible, como correr los cien metros por debajo de 8 segundos con cota de mallas o esquivar una bala no por suerte, sino viéndola venir y calculando su trayectoria.',
      ],
      [
        'Inhumano INH',
        '320',
        'Sencillamente es algo que en nuestro mundo, en la realidad, no se puede físicamente realizar. Son cosas que van en contra de la lógica de una manera limitada, como levantar una camioneta a pulso, subir a un tercer piso de un salto o correr entre una lluvia de balas de alta velocidad esquivándolas sin problemas. La misma habilidad por tirada no basta para alcanzar algo así a la hora de realizar estas proezas. Es necesario que los personajes tengan acceso a realizar acciones inhumanas para alcanzar esta dificultad.',
      ],
      [
        'Zen ZEN',
        '440',
        'Son actos que de por sí rompen totalmente la lógica de aquello que llamamos realidad, como recorrer más de mil metros por debajo de un segundo o saltarlos verticalmente sin preparación. Al igual que la Inhumanidad, la mera habilidad no permite realizar acciones de Zen, por lo que el personaje tendrá que poseer sobrenaturalmente la capacidad de hacerlas.',
      ],
    ],
  },
  {
    name: 'Atletismo',
    header: [
      'Cantidad',
      'Tipo de Movimiento',
      'Corriendo',
      'Movimiento Máximo',
    ],
    body: [
      ['-', '', '1 Minuto', '1 asalto'],
      ['40', '', '5 minutos', '2 asaltos'],
      ['80', '', '10 minutos', '5 asaltos'],
      ['120', '', '20 minutos', '10 asaltos'],
      ['140', '', '40 minutos', '15 asaltos'],
      ['180', '+1', '1 hora', '1 minuto'],
      ['240', '+1', '2 horas', '2 minutos'],
      ['280', '+2', '5 horas', '3 minutos'],
      ['320', '+2', '1 día', '5 minutos'],
    ],
  },
  {
    name: 'Nadar',
    header: [
      'Cantidad',
      'Dificultad',
      'Tipo de Movimiento',
    ],
    body: [
      ['-', '', '-8'],
      ['40', 'Fácil', '-5'],
      ['80', 'Media', '-4'],
      ['120', 'Difícil', '-3'],
      ['140', 'Muy Difícil', '-3'],
      ['180', 'Absurdo', '-2'],
      ['240', 'Casi Imposible', '-2'],
      ['280', 'Imposible', '-1'],
      ['320', 'Inhumano', '0'],
    ],
  },
  {
    name: 'Saltar',
    header: [
      'Cantidad',
      'Dificultad',
      'Tipo de Movimiento',
    ],
    body: [
      ['-', '', '-1'],
      ['40', 'Fácil', '+0'],
      ['80', 'Media', '+0'],
      ['120', 'Difícil', '+1'],
      ['140', 'Muy Difícil', '+1'],
      ['180', 'Absurdo', '+2'],
      ['240', 'Casi Imposible', '+2'],
      ['280', 'Imposible', '+4'],
      ['320', 'Inhumano', '+5'],
    ],
  },
  {
    name: 'Modificadores a la Percepción',
    header: ['', 'Modificador'],
    body: [
      ['Vista', '||||||'],
      ['Zona parcialmente oscura', '-30'],
      ['Oscuridad completa', '-60'],
      ['Lluvia', '-20'],
      [
        'El blanco sólo es visible en parte',
        '-30',
      ],
      [
        'Blanco camuflado como el ambiente',
        '-30',
      ],
      [
        'El color contrasta con el ambiente',
        '+40',
      ],
      ['El personaje está preparado', '+20'],
      ['Posición superior o elevada', '+30'],
      ['Oído', '||||||'],
      ['Ligero ruido de fondo', '-20'],
      ['Personas hablando', '-40'],
      ['Ruidos estridentes', '-80'],
      ['Olfato', '||||||'],
      ['Olor obvio', '+30'],
      ['Varios olores presentes', '-30'],
      ['Tacto', '||||||'],
      ['Llevando guantes', '-40'],
      ['Gusto', '||||||'],
      ['Sabor conocido', '+40'],
      ['Paladar inactivo', '-40'],
    ],
  },
  {
    name: 'Tratamiento de Heridas',
    header: [
      'Cantidad',
      'Dificultad',
      'Recuperación',
    ],
    body: [
      ['40', 'Fácil', 'Detener hemorragia'],
      ['80', 'Media', 'Estabilizar'],
      ['120', 'Difícil', '+10% del daño'],
      ['140', 'Muy', 'Difícil +20% del daño'],
      ['180', 'Absurdo', '+30% del daño'],
      ['240', 'Casi', 'Imposible +40% del daño'],
      ['280', 'Imposible', '+50% del daño'],
      ['320', 'Inhumano', '+70% del daño'],
    ],
  },
  {
    name: 'Frialdad',
    header: ['Cantidad', 'Dificultad', 'Bono'],
    body: [
      ['40', 'Fácil', '+5'],
      ['80', 'Media', '+10'],
      ['120', 'Difícil', '+15'],
      ['140', 'Muy Difícil', '+20'],
      ['180', 'Absurdo', '+25'],
      ['240', 'Casi Imposible', '+30'],
      ['280', 'Imposible', '+35'],
      ['320', 'Inhumano', '+40'],
    ],
  },
  {
    name: 'Proezas de Fuerza',
    header: [
      'Cantidad',
      'Dificultad',
      'Modificador a la Fuerza',
    ],
    body: [
      ['120', 'Difícil', 'Fuerza +1'],
      ['180', 'Absurdo', 'Fuerza +2'],
      ['240', 'Casi Imposible', 'Fuerza +3'],
      ['280', 'Imposible', 'Fuerza +4'],
    ],
  },
  {
    name: 'Resistir El Dolor',
    header: [
      'Cantidad',
      'Dificultad',
      'Negativo anulado',
    ],
    body: [
      ['80', 'Media', '-10'],
      ['120', 'Difícil', '-20'],
      ['140', 'Muy Difícil', '-30'],
      ['180', 'Absurdo', '-40'],
      ['240', 'Casi Imposible', '-50'],
      ['280', 'Imposible', '-60'],
      ['320', 'Inhumano', '-70'],
      ['440', 'Zen', '-80'],
    ],
  },
  {
    name: 'Disfraz',
    header: ['Situación', 'Bono'],
    body: [
      [
        'Menos de un minuto de preparación',
        '-20',
      ],
      ['Sobre una hora de preparación', '+20'],
      ['Varias horas de preparación', '+40'],
      ['Sin material para disfrazarse', '-40'],
      ['Material improvisado', '-20'],
      ['Material apropiado', '+20'],
      ['Trajes y maquillaje preparados', '+40'],
    ],
  },
  {
    name: 'Ocultarse',
    header: ['Situación', 'Bono'],
    body: [
      ['Tamaño grande', '-20'],
      ['Tamaño pequeño', '+20'],
      ['Delante de un individuo', '-200'],
      ['Lugar propicio para esconderse', '+40'],
      ['Zona con sombras', '+20'],
      ['Lugar iluminado', '-20'],
      ['Zona vacía', '-80'],
    ],
  },
  {
    name: 'Trampería',
    header: [
      'Cantidad',
      'Dificultad',
      'Nivel de la trampa',
    ],
    body: [
      ['20', 'Rutinario', 'Nivel 10'],
      ['40', 'Fácil', 'Nivel 20'],
      ['80', 'Media', 'Nivel 30'],
      ['120', 'Difícil', 'Nivel 40'],
      ['140', 'Muy Difícil', 'Nivel 50'],
      ['180', 'Absurdo', 'Nivel 60'],
      ['240', 'Casi Imposible', 'Nivel 70'],
      ['280', 'Imposible', 'Nivel 80'],
      ['320', 'Inhumano', 'Nivel 90'],
      ['440', 'Zen', 'Nivel 100'],
    ],
  },
  {
    name: 'Preparación de Trampas',
    header: ['Situación', 'Bono'],
    body: [
      [
        'Menos de un minuto de preparación',
        '-60',
      ],
      ['Unas horas de preparación', '+0'],
      ['Unos días de preparación', '+40'],
      ['Semanas de preparación', '+80'],
      ['Material improvisado', '-40'],
      [
        'Material exclusivamente preparado',
        '+40',
      ],
    ],
  },
  {
    name: 'Venenos',
    header: [
      'Cantidad',
      'Dificultad',
      'Nivel del Veneno',
    ],
    body: [
      ['40', 'Fácil', 'Nivel 10'],
      ['80', 'Media', 'Nivel 20'],
      ['120', 'Difícil', 'Nivel 30'],
      ['140', 'Muy Difícil', 'Nivel 40'],
      ['180', 'Absurdo', 'Nivel 50'],
      ['240', 'Casi Imposible', 'Nivel 60'],
      ['280', 'Imposible', 'Nivel 70'],
      ['320', 'Inhumano', 'Nivel 80'],
      ['440', 'Zen', 'Nivel 90'],
    ],
  },
  {
    name: 'Preparación Para La Forja',
    header: ['Tiempo empleado', 'Bono'],
    body: [
      ['Una hora', '-60'],
      ['Unas tres o cuatro horas', '-40'],
      ['Un día', '-20'],
      ['Dos o tres días', '-10'],
      ['Una semana', '0'],
      ['Dos semanas', '+10'],
      ['Un mes', '+20'],
      ['Dos o tres meses', '+40'],
      ['Seis meses', '+60'],
      ['Un año', '+80'],
      ['Tres o cuatro años', '+100'],
      ['Unos diez años', '+120'],
    ],
  },
  {
    name: 'Forja',
    header: [
      'Dificultad',
      'Cantidad',
      'Armas',
      'Armaduras',
      'Yelmos',
      'Otros',
    ],
    body: [
      [
        'Fácil',
        '40',
        'Flecha de descarga, Flecha de fajo, Garrote, Vara',
        '',
        'Anilla, Capucha de cuero, Frentón',
        'Herraduras, Hebillas, Enganches, Chapas, Cubiertos, Cazos, Sartenes',
      ],
      [
        'Media',
        '80',
        'Arpón,Bala,Bolas,Cadena,Daga,Dardos,Dardos de cerbatana, Dardos de mano, Garfio, Guadaña, Gran martillo de guerra, Hacha de mano,Honda,Jabalina,Lanza,Lazo,Mangual,Martillo de Guerra,Mayal, Maza,Maza pesada a dos manos, Tonga',
        'Acolchada,Completa de cuero,Cuero,Cuero endurecido,Piel',
        'Coronilla',
        'Bisutería,Candelabros',
      ],
      [
        'Difícil',
        '120',
        'Abanico de combate,Alabarda,Arco Corto,Arco Largo,Boleadoras,Cerbatana,Cimitarra,Cuervo,Daga de parada,Escudo corporal,Espada ancha,Espada bastarda, Espada corta, Espada larga, Estilete, Flecha de mella, Garras, Hacha a dos manos, Hacha de guerra, Kusari-Gama,Lanza de caballería, Látigo,Nunchaku,Red de gladiador, Rodela, Shuriken, Tridente',
        'Anillas, Cuero Tachonado, Gabardina Armada, Mallas, Peto,Piezas',
        'Capucha de Mallas, Completo abierto',
        'Bisutería elaborada, Bardas',
      ],
      [
        'Muy Difícil',
        '140',
        'Arco Largo Compuesto, Ballesta, Ballesta Pesada, Bumerán,Cestus, Estoque, Florete, Katana, Katar, Mandoble, No-Dachi, Quebradora, Sable, Sai, Shuko, Tanto',
        'Escamas, Placas,Semiformal',
        'Completo Cerrado',
        'Lámparas, Artesanía fina',
      ],
      [
        'Absurdo',
        '180',
        'Anciano de Primavera, Katana de Dos Hojas, Turcus,Arcabuz, Ballesta de Mano, Ballesta de Repetición, Pistola de Mecha',
        'Completa, Completa Pesada, Completa de Campaña',
        '',
        'Lentes, Relojes, Catalejos, Brújulas',
      ],
    ],
  },
  {
    name: 'indice de regeneración',
    header: ['Constitución', 'Regeneración'],
    body: [
      ['1 a 2', 'Ninguna'],
      ['3 a 7', '1'],
      ['8 a 9', '2'],
      ['10', '3'],
      ['11', '4'],
      ['12', '5'],
      ['13', '6'],
      ['14', '7'],
      ['15', '8'],
      ['16', '9'],
      ['17', '10'],
      ['18', '11'],
      ['19 o 20', '12'],
    ],
  },
  {
    name: 'Índices de curación',
    header: [
      'Nivel de regeneración',
      'Descansando',
      'Sin descanso',
      'Reducción de negativos',
      'capacidades especiales',
    ],
    body: [
      [
        '1',
        '10 al día',
        '5 al día',
        '-5 al día',
        '',
      ],
      [
        '2',
        '20 al día',
        '10 al día',
        '-5 al día',
        '',
      ],
      [
        '3',
        '30 al día',
        '15 al día',
        '-5 al día',
        '',
      ],
      [
        '4',
        '40 al día',
        '20 al día',
        '-10 al día',
        '',
      ],
      [
        '5',
        '50 al día',
        '25 al día',
        '-10 al día',
        'No quedan cicatrices',
      ],
      [
        '6',
        '75 al día',
        '30 al día',
        '-15 al día',
        'El personaje no sufre efectos del desangramiento',
      ],
      [
        '7',
        '100 al día',
        '50 al día',
        '-20 al día',
        'los miembros limpiamente amputados se recuperan si se unen al muñón durante una semana',
      ],
      [
        '8',
        '250 al día',
        '100 al día',
        '-25 al día',
        'Como el anterior, pero en cinco días',
      ],
      [
        '9',
        '500 al día',
        '200 al día',
        '-30 al día',
        'Como el anterior, pero en tres días. El personaje supera automáticamente el estado entre la vida y la muerte',
      ],
      [
        '10',
        '1 por minuto',
        'NA',
        '-40 al día',
        'Como el anterior, pero en un día',
      ],
      [
        '11',
        '2 por minuto',
        'NA',
        '-50 al día',
        'Cualquier miembro amputado se recupera, uniendo los restos al muñón durante una semana',
      ],
      [
        '12',
        '5 por minuto',
        'NA',
        '-5 por hora',
        'Como el anterior, pero en 3 días',
      ],
      [
        '13',
        '10 por minuto',
        'NA',
        '-10 por hora',
        'Como el anterior, pero en un día',
      ],
      [
        '14',
        '1 por asalto',
        'NA',
        '-15 por hora',
        'Cualquier miembro se recupera, uniéndolo al muñón durante unas pocas horas',
      ],
      [
        '15',
        '5 por asalto',
        'NA',
        '-20 por hora',
        'Cualquier miembro se recupera inmediatamente si se une al muñón durante un asalto. Salvo la cabeza, cualquier miembro amputado vuelve a crecer en una semana',
      ],
      [
        '16',
        '10 por asalto',
        'NA',
        '-10 por minuto',
        'Salvo la cabeza, cualquier miembro amputado vuelve a crecer en un día',
      ],
      [
        '17',
        '25 por asalto',
        'NA',
        '-10 por asalto',
        'Salvo la cabeza, cualquier miembro amputado vuelve a crecer en pocos minutos',
      ],
      [
        '18',
        '50 por asalto',
        'NA',
        '-25 por asalto',
        'Salvo la cabeza, cualquier miembro amputado vuelve a crecer en pocos asaltos',
      ],
      [
        '19',
        '100 por asalto',
        'NA',
        'Todos',
        'Cualquier miembro seccionado crece y es completamente funcional en un asalto',
      ],
      [
        '20',
        '250 por asalto',
        'NA',
        'Todos',
        'Todos los críticos físicos son anulados',
      ],
    ],
  },
  {
    name: 'Tipo de movimiento',
    header: [
      'Tipo de movimiento',
      'Distancia máxima por asalto',
      'Requiere',
    ],
    body: [
      ['1', 'Menos de un metro', ''],
      ['2', '4 metros', ''],
      ['3', '4 metros', ''],
      ['4', '4 metros', ''],
      ['5', '4 metros', ''],
      ['6', '4 metros', ''],
      ['7', '4 metros', ''],
      ['8', '4 metros', ''],
      ['9', '4 metros', ''],
      ['10', '4 metros', ''],
      ['11', '4 metros', 'Inhumanidad'],
      ['12', '4 metros', 'Inhumanidad'],
      ['13', '4 metros', 'Inhumanidad'],
      ['14', '4 metros', 'Zen'],
      ['15', '4 metros', 'Zen'],
      ['16', '4 metros', 'Zen'],
      ['17', '4 metros', 'Zen'],
      ['18', '4 metros', 'Zen'],
      ['19', '4 metros', 'Zen'],
      ['20', '4 metros', 'Zen'],
    ],
  },
  {
    name: 'Índice de peso',
    header: [
      'Índice de peso',
      'Peso natural',
      'Carga máxima',
      'Requiere',
    ],
    body: [
      ['1', 'Menos de un Kg.', 'Un Kg', ''],
      ['2', '5 Kg.', '10 Kg.', ''],
      ['3', '10 Kg.', '20 Kg.', ''],
      ['4', '15 Kg.', '40 Kg.', ''],
      ['5', '25 Kg.', '60 Kg.', ''],
      ['6', '40 Kg.', '120 Kg.', ''],
      ['7', '60 Kg.', '180 Kg.', ''],
      ['8', '80 Kg.', '260 Kg.', ''],
      ['9', '100 Kg.', '350 Kg.', ''],
      ['10', '150 Kg.', '420 Kg.', ''],
      ['11', '200 Kg.', '600 Kg.', 'Inhumanidad'],
      ['12', '350 Kg.', '1 Ton.', 'Inhumanidad'],
      ['13', '1 Ton.', '3 Ton.', 'Inhumanidad'],
      ['14', '5 Ton.', '25 Ton.', 'Zen'],
      ['15', '15 Ton.', '100 Ton.', 'Zen'],
      ['16', '100 Ton.', '500 Ton.', 'Zen'],
      ['17', '500 Ton.', '2.500 Ton.', 'Zen'],
      ['18', '1.000 Ton.', '10.000 Ton.', 'Zen'],
      [
        '19',
        '10.000 Ton.',
        '150.000 Ton.',
        'Zen',
      ],
      ['20', 'Especial', 'Especial', 'Zen'],
    ],
  },
  {
    name: 'Cansancio',
    header: ['Cansancio', 'Negativo a la acción'],
    body: [
      ['0', '-120'],
      ['1', '-80'],
      ['2', '-40'],
      ['3', '-20'],
      ['4', '-10'],
    ],
  },
  {
    name: 'Necesidades físicas',
    header: ['Situación', 'Negativo'],
    body: [
      ['Un dia sin comer', '-10'],
      ['Un dia sin beber', '-15'],
      ['No dormir', '-20'],
      ['Dormir menos de 1 hora', '-10'],
    ],
  },
  {
    name: 'Modificadores a la habilidad',
    header: [
      'Tipo',
      'Penalizador a la habilidad',
    ],
    body: [
      ['Arma similar', '-20'],
      ['Arma mixta', '-40'],
      ['Arma distinta/desarmado', '-60'],
      ['Parada y Esquiva', '-60'],
    ],
  },
  {
    name: 'Armas comunes',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Alabarda',
        '60',
        '-15',
        '6/11',
        'FIL',
        'CON',
        'Asta/Mandoble',
        'A dos manos',
        '15',
        '4',
        '20',
      ],
      [
        'Arpón',
        '35',
        '-5',
        '5',
        'PEN',
        '',
        'Asta',
        'A dos manos, Lanzable',
        '11',
        '0',
        '15',
      ],
      [
        'Cadena',
        '25',
        '+0',
        '6',
        'CON',
        '',
        'Asta',
        'Cuerda, Compleja, Pesa (Fuerza 8)',
        '13',
        '2',
        '15',
      ],
      [
        'Cestus',
        '25',
        '+10',
        '3',
        'PEN',
        'FIl',
        'Arma corta',
        '',
        '11',
        '-2',
        '15',
      ],
      [
        'Cimitarra',
        '50',
        '+5',
        '5',
        'FIL',
        '',
        'Espada',
        '',
        '13',
        '4',
        '20',
      ],
      [
        'Cimitarra',
        '50',
        '+5',
        '5',
        'FIL',
        '',
        'Espada',
        '',
        '13',
        '4',
        '20',
      ],
      [
        'Daga',
        '30',
        '+20',
        '3',
        'PEN',
        'FIL',
        'Arma corta',
        'Lanzable, Precisa',
        '10',
        '-2',
        '15',
      ],
      [
        'Daga de parada',
        '30',
        '+15',
        '3',
        'PEN',
        'FIL',
        'Arma corta',
        'Lanzable, Traba el arma, Precisa',
        '12',
        '0',
        '20',
      ],
      [
        'Espada ancha',
        '55',
        '-5',
        '5',
        'FIL',
        '',
        'Espada',
        '',
        '15',
        '3',
        '25',
      ],
      [
        'Espada bastarda',
        '70',
        '-30',
        '7/9',
        'FIL',
        'CON',
        'Espada / Mandoble',
        'A una o dos manos',
        '15',
        '5',
        '25',
      ],
      [
        'Espada corta',
        '40',
        '+15',
        '4',
        'PEN',
        'FIL',
        'Arma corta',
        'Precisa',
        '12',
        '1',
        '20',
      ],
      [
        'Espada larga',
        '50',
        '+0',
        '6',
        'FIL',
        '',
        'Espada',
        '',
        '13',
        '3',
        '25',
      ],
      [
        'Estilete',
        '25',
        '+20',
        '3',
        'PEN',
        '',
        'Arma corta',
        'Lanzable, precisa',
        '8',
        '-3',
        '15',
      ],
      [
        'Estoque',
        '40',
        '+15',
        '4',
        'PEN',
        'FIL',
        'Espada',
        'Precisa',
        '11',
        '2',
        '20',
      ],
      [
        'Florete',
        '35',
        '+15',
        '3',
        'PEN',
        '',
        'Espada / Arma corta',
        'Precisa',
        '9',
        '-2',
        '20',
      ],
      [
        'Garfio',
        '30',
        '+10',
        '3',
        'PEN',
        '',
        'Arma corta',
        '',
        '11',
        '-2',
        '15',
      ],
      [
        'Garrote',
        '30',
        '+0',
        '5',
        'CON',
        '',
        'Maza',
        '',
        '11',
        '-2',
        '15',
      ],
      [
        'Gran martillo de guerra',
        '70',
        '-35',
        '7/10',
        'CON',
        '',
        'Maza',
        'A una o dos manos',
        '16',
        '6',
        '20',
      ],
      [
        'Guadaña',
        '35',
        '+0',
        '5/9',
        'FIL',
        'CON',
        'Asta / Mandoble',
        'A una o dos manos',
        '12',
        '2',
        '25',
      ],
      [
        'Hacha a dos manos',
        '100',
        '-70',
        '9/11',
        'FIL',
        'CON',
        'Hacha / Mandoble',
        'A una o dos manos',
        '17',
        '7',
        '30',
      ],
      [
        'Hacha de guerra',
        '70',
        '-30',
        '7',
        'FIL',
        'CON',
        'Hacha',
        'Lanzable',
        '15',
        '5',
        '25',
      ],
      [
        'Hacha de mano',
        '45',
        '+0',
        '5',
        'FIL',
        '',
        'Hacha',
        'Lanzable',
        '13',
        '4',
        '15',
      ],
      [
        'Jabalina',
        '35',
        '+5',
        '4',
        'PEN',
        '',
        'Asta',
        'Lanzable',
        '10',
        '-2',
        '20',
      ],
      [
        'Lanza',
        '40',
        '+5',
        '4/6',
        'PEN',
        '',
        'Asta',
        'Lanzable, A una o dos manos',
        '13',
        '2',
        '25',
      ],
      [
        'Lanza de caballería',
        '80',
        '-30',
        '8',
        'PEN',
        '',
        'Asta',
        'Ver',
        '12',
        '7',
        '25',
      ],
      [
        'Látigo',
        '35',
        '-20',
        '4',
        'FIL',
        'CON',
        'Cuerda',
        'Compleja, Presa (fuerza 8)',
        '9',
        '-3',
        '20',
      ],
      [
        'Lazo',
        '5',
        '+0',
        '4',
        'CON',
        '',
        'Cuerda',
        'Compleja, Presa (fuerza 9), ver',
        '9',
        '-4',
        '20',
      ],
      [
        'Mandoble',
        '90',
        '-60',
        '8/10',
        'FIL',
        'CON',
        'Mandoble',
        'A una o dos manos',
        '18',
        '6',
        '30',
      ],
      [
        'Mangual',
        '80',
        '-50',
        '8/10',
        'CON',
        '',
        'Maza / Mandoble',
        'Compleja',
        '14',
        '6',
        '20',
      ],
      [
        'Martillo de guerra',
        '50',
        '-5',
        '6',
        'CON',
        '',
        'Maza',
        '',
        '15',
        '4',
        '15',
      ],
      [
        'Mayal',
        '40',
        '+0',
        '6',
        'CON',
        '',
        'Maza / Cuerda',
        'Compleja',
        '13',
        '4',
        '15',
      ],
      [
        'Maza',
        '40',
        '+0',
        '6',
        'CON',
        '',
        'Maza',
        '',
        '14',
        '4',
        '15',
      ],
      [
        'Maza pesada de combate',
        '60',
        '-15',
        '6/10',
        'CON',
        '',
        'Maza / Mandoble',
        'A una o dos manos',
        '16',
        '5',
        '15',
      ],
      [
        'Red de gladiador',
        '5',
        '+0',
        '4',
        'CON',
        'FIL',
        'Cuerda',
        'Lanzable, Presa (Fuerza 10), ver',
        '13',
        '-4',
        '15',
      ],
      [
        'Sable',
        '45',
        '+10',
        '6',
        'FIL',
        'PEN',
        'Espada',
        '',
        '12',
        '3',
        '20',
      ],
      [
        'Tridente',
        '40',
        '-10',
        '6/7',
        'PEN',
        '',
        'Asta',
        'Lanzable, A dos manos',
        '12',
        '3',
        '15',
      ],
      [
        'Vara',
        '30',
        '+10',
        '4',
        'CON',
        '',
        'Asta',
        'A dos manos',
        '11',
        '0',
        '30',
      ],
      [
        'Combate desarmado',
        '10',
        '+20',
        '-',
        'CON',
        '',
        'Sin armas',
        'Precisa',
        '-',
        '-2',
        '-',
      ],
    ],
  },
  {
    name: 'Armas exóticas de diseño',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Katana',
        '50',
        '+0',
        '5/6',
        'FIL',
        '',
        'Espada',
        'A una o dos manos',
        '11',
        '3',
        '40',
      ],
      [
        'Katar',
        '40',
        '+10',
        '8',
        'PEN',
        'FIL',
        'Arma corta',
        'Compleja, ver',
        '13',
        '3',
        '25',
      ],
      [
        'Garras',
        '30',
        '+15',
        '4',
        'FIL',
        'PEN',
        'Arma corta',
        '',
        '12',
        '2',
        '15',
      ],
      [
        'Nunchaku',
        '30',
        '+15',
        '5',
        'CON',
        '',
        'Cuerda',
        '',
        '11',
        '0',
        '15',
      ],
      [
        'Bumerán',
        '30',
        '+10',
        '4',
        'CON',
        'FIL',
        'Arma corta',
        'Lanzable, ver',
        '10',
        '0',
        '15',
      ],
      [
        'Quebradora',
        '50',
        '-20',
        '8/10',
        'CON',
        'FIL',
        'Mandoble',
        'A una o dos manos',
        '16',
        '8',
        '25',
      ],
      [
        'Shuriken',
        '25',
        '+20',
        '4',
        'FIL',
        'PEN',
        'Arma corta',
        'Lanzable',
        '10',
        '1',
        '20',
      ],
      [
        'Cuervo',
        '35',
        '+10',
        '4',
        'CON',
        'FIL',
        'Arma corta',
        'Compleja, Precisa, ver',
        '11',
        '2',
        '25',
      ],
      [
        'Anciano de primavera',
        '35',
        '+15',
        '4',
        'FIL',
        'PEN',
        'Asta',
        'Compleja, A dos manos, ver',
        '12',
        '2',
        '25',
      ],
      [
        'Katana de doble hoja',
        '55',
        '-5',
        '8',
        'FIL',
        '',
        'Espada',
        'ver',
        '11',
        '3',
        '40',
      ],
      [
        'Nodachi',
        '80',
        '-35',
        '8/10',
        'FIL',
        '',
        'Mandoble',
        'A una o dos manos',
        '14',
        '4',
        '40',
      ],
      [
        'Tanto',
        '40',
        '+25',
        '3',
        'FIL',
        '',
        'Arma corta',
        'Precisa',
        '9',
        '1',
        '40',
      ],
      [
        'Tonfa',
        '30',
        '+20',
        '4',
        'CON',
        '',
        'Arma corta',
        'Precisa',
        '13',
        '0',
        '25',
      ],
      [
        'Abanico de combate',
        '30',
        '+20',
        '4',
        'FIL',
        'CON',
        'Arma corta',
        'Precisa, Lanzable',
        '8',
        '0',
        '25',
      ],
      [
        'Sai',
        '35',
        '+15',
        '4',
        'PEN',
        'FIL',
        'Arma corta',
        'Precisa, Traba el arma',
        '12',
        '0',
        '25',
      ],
      [
        'Kusari-Gama',
        '40',
        '+5',
        '5',
        'FIL',
        'CON',
        'Arma corta / Cuerda',
        'A dos manos, Presa (Fuerza 8), ver',
        '12',
        '4',
        '25',
      ],
      [
        'Shuko',
        '20',
        '+10',
        '4',
        'PEN',
        '',
        'Arma corta',
        'ver',
        '9',
        '-2',
        '25',
      ],
    ],
  },
  {
    name: 'Armas improvisadas',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Botella rota',
        '15',
        '+10',
        '3',
        'FIL',
        'CON',
        'Arma corta',
        '',
        '5',
        '-3',
        '15',
      ],
      [
        'Silla',
        '25',
        '-20',
        '5',
        'CON',
        '',
        'Mandoble',
        'A dos manos',
        '2',
        '0',
        '20',
      ],
      [
        'Palo de madera',
        '20',
        '+0',
        '4',
        'CON',
        '',
        'Maza',
        '',
        '8',
        '-1',
        '10',
      ],
      [
        'Barra metálica',
        '25',
        '-5',
        '5',
        'CON',
        '',
        'Maza',
        '',
        '12',
        '2',
        '15',
      ],
      [
        'Jarrón',
        '15',
        '-10',
        '4',
        'CON',
        '',
        'Maza',
        'Lanzable',
        '6',
        '-2',
        '20',
      ],
      [
        'Cuchillo de cocina',
        '25',
        '+10',
        '4',
        'FIL',
        '',
        'Arma corta',
        '',
        '9',
        '-1',
        '10',
      ],
      [
        'Martillo',
        '30',
        '-20',
        '4',
        'CON',
        '',
        'Maza',
        '',
        '12',
        '2',
        '10',
      ],
      [
        'Hacha de leñador',
        '40',
        '-10',
        '5/7',
        'FIL',
        '',
        'Hacha',
        'A una o dos manos',
        '12',
        '3',
        '15',
      ],
      [
        'Azada',
        '30',
        '-20',
        '4',
        'FIL',
        'CON',
        'Hacha',
        '',
        '10',
        '1',
        '15',
      ],
      [
        'Hoz',
        '35',
        '-10',
        '4',
        'FIL',
        'PEN',
        'Arma corta',
        '',
        '8',
        '0',
        '15',
      ],
      [
        'Pico',
        '40',
        '-20',
        '5',
        'PEN',
        '',
        'Arma corta',
        '',
        '10',
        '-2',
        '20',
      ],
      [
        'Antorcha',
        '20',
        '-10',
        '4',
        'CON',
        'CAL',
        'Maza',
        '',
        '10',
        '-2',
        '20',
      ],
    ],
  },
  {
    name: 'Escudos',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Rodela',
        '15',
        '-15 esp',
        '5',
        'CON',
        '',
        'Escudo',
        '+10 a la parada, +5 a la esquiva, ver',
        '14',
        '0',
        '20',
      ],
      [
        'Escudo',
        '20',
        '-25 esp',
        '7',
        'CON',
        '',
        'Escudo',
        '+20 a la parada, +10 a la esquiva, ver',
        '16',
        '0',
        '25',
      ],
      [
        'Escudo corporal',
        '25',
        '-40 esp',
        '10',
        'CON',
        '',
        'Escudo',
        '+30 a la parada, +15 a la esquiva, ver',
        '18',
        '1',
        '25',
      ],
    ],
  },
  {
    name: 'Recarga y cadencia de fuego',
    header: [
      'ARMA',
      'Tipo',
      'Cadencia de fuego',
      'Recarga',
      'Alcance',
    ],
    body: [
      [
        'Abanico de combate',
        'Lanzable',
        '40',
        '',
        '20m',
      ],
      ['Arcabuz', 'Disparo', '', '4', '80m'],
      [
        'Arco compuesto',
        'Disparo',
        '',
        '1',
        '90m',
      ],
      ['Arco corto', 'Disparo', '', '1', '40m'],
      ['Arco largo', 'Disparo', '', '1', '60m'],
      ['Arpón', 'Lanzable', '100', '', '20m'],
      [
        'Balista ligera',
        'Disparo',
        '',
        '10',
        '150m',
      ],
      [
        'Balista pesada',
        'Disparo',
        '',
        '12',
        '200m',
      ],
      ['Ballesta', 'Disparo', '', '2', '60m'],
      [
        'Ballesta de mano',
        'Disparo',
        '',
        '2',
        '30m',
      ],
      [
        'Ballesta de repetición',
        'Disparo',
        '',
        '3',
        '60m',
      ],
      [
        'Ballesta pesada',
        'Disparo',
        '',
        '2',
        '80m',
      ],
      ['Bolas', 'Lanzable', '50', '', '20m'],
      ['Boleadoras', 'Lanzable', '80', '', '20m'],
      ['Bumerán', 'Lanzable', '60', '', '20m'],
      ['Cañón', 'Disparo', '', '12', '250m'],
      ['Cerbatana', 'Disparo', '', '1', '50m'],
      ['Daga', 'Lanzable', '50', '', '20m'],
      [
        'Daga de parada',
        'Lanzable',
        '50',
        '',
        '15m',
      ],
      [
        'Dardos de mano',
        'Lanzable',
        '40',
        '',
        '20m',
      ],
      ['Estilete', 'Lanzable', '30', '', '30m'],
      [
        'Hacha de guerra',
        'Lanzable',
        '100',
        '',
        '5m',
      ],
      [
        'Hacha de mano',
        'Lanzable',
        '80',
        '',
        '10m',
      ],
      ['Honda', 'Disparo', '80', '1', '50m'],
      ['Jabalina', 'Lanzable', '80', '', '30m'],
      ['Lanza', 'Lanzable', '80', '', '30m'],
      [
        'Pistola de mecha',
        'Disparo',
        '',
        '4',
        '50m',
      ],
      ['Shuriken', 'Lanzable', '30', '', '20m'],
      [
        'Res de gladiador',
        'Lanzable',
        '100',
        '',
        '5m',
      ],
      ['Tridente', 'Lanzable', '100', '', '15m'],
      ['Turcus', 'Lanzable', '80', '', '30m'],
    ],
  },
  {
    name: 'Armas de proyectiles',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Ballesta',
        '',
        '+0',
        '4/8',
        '',
        '',
        'Proyectil',
        'Fuerza 8, A una o dos manos, Ver',
        '8',
        '-2',
        '20',
      ],
      [
        'Saeta',
        '40',
        '',
        '',
        'PEN',
        '',
        'Munición',
        '',
        '3',
        '0',
        '15',
      ],
      [
        'Ballesta de repetición',
        '',
        '+0',
        '5/8',
        '',
        '',
        'Proyectil',
        'Fuerza 8, A una o dos manos, Ver',
        '6',
        '-2',
        '20',
      ],
      [
        'Saeta',
        '40',
        '',
        '',
        'PEN',
        '',
        'Munición',
        '',
        '3',
        '0',
        '15',
      ],
      [
        'Ballesta pesada',
        '',
        '-20',
        '7/10',
        '',
        '',
        'Proyectil',
        'Fuerza 8, A una o dos manos, Ver',
        '8',
        '-1',
        '20',
      ],
      [
        'Saeta pesada',
        '60',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para ballestas pesadas',
        '4',
        '1',
        '15',
      ],
      [
        'Ballesta de mano',
        '',
        '+10',
        '3',
        '',
        '',
        'Proyectil',
        'Fuerza 8, Ver',
        '5',
        '-4',
        '15',
      ],
      [
        'Saeta ligera',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para ballestas ligeras',
        '2',
        '-1',
        '15',
      ],
      [
        'Arco corto',
        '',
        '-10',
        '4',
        '',
        '',
        'Proyectil',
        'A dos manos',
        '7',
        '-3',
        '15',
      ],
      [
        'Flecha de fajo',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, Ver',
        '3',
        '0',
        '20',
      ],
      [
        'Flecha de descarga',
        '40',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos',
        '4',
        '1',
        '20',
      ],
      [
        'Flecha de mella',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, ver',
        '3',
        '0',
        '20',
      ],
      [
        'Arco largo',
        '',
        '-30',
        '7',
        '',
        '',
        'Proyectil',
        'A dos manos',
        '8',
        '-2',
        '20',
      ],
      [
        'Flecha de fajo',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, Ver',
        '3',
        '0',
        '20',
      ],
      [
        'Flecha de descarga',
        '40',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos',
        '4',
        '1',
        '20',
      ],
      [
        'Flecha de mella',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, ver',
        '3',
        '0',
        '20',
      ],
      [
        'Arco compuesto',
        '',
        '-30',
        '7',
        '',
        '',
        'Proyectil',
        'A dos manos',
        '8',
        '-2',
        '25',
      ],
      [
        'Flecha de fajo',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, Ver',
        '3',
        '0',
        '20',
      ],
      [
        'Flecha de descarga',
        '40',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos',
        '4',
        '1',
        '20',
      ],
      [
        'Flecha de mella',
        '30',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para los arcos, ver',
        '3',
        '0',
        '20',
      ],
      [
        'Boleadoras',
        '30',
        '-10',
        '5',
        'CON',
        '',
        'Lanzamiento',
        'Presa (Fue 10), Compleja, Ver',
        '6',
        '2',
        '15',
      ],
      [
        'Bolas',
        '20',
        '+0',
        '5',
        'CON',
        '',
        'Lanzamiento',
        '',
        '10',
        '2',
        '15',
      ],
      [
        'Dardos de mano',
        '20',
        '+20',
        '3',
        'PEN',
        '',
        'Lanzamiento',
        '',
        '3',
        '-4',
        '15',
      ],
      [
        'Turcus',
        '40',
        '+0',
        '6',
        'FIL',
        '',
        'Lanzamiento',
        'Ver',
        '9',
        '2',
        '20',
      ],
      [
        'Cerbatana',
        '',
        '-10',
        '4',
        '',
        '',
        'Proyectil',
        '',
        '3',
        '-3',
        '15',
      ],
      [
        'Dardos de cerbatana',
        '5',
        '',
        '',
        'PEN',
        '',
        'Munición',
        '',
        '2',
        '-4',
        '15',
      ],
      [
        'Pistola de mecha',
        '',
        '+0',
        '4',
        '',
        '',
        'Proyectil',
        'Fuerza 9, Compleja, Ver',
        '8',
        '-3',
        '20',
      ],
      [
        'Bala',
        '60',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para pistolas',
        '11',
        '5',
        '15',
      ],
      [
        'Arcabuz',
        '',
        '-20',
        '6',
        '',
        '',
        'Proyectil',
        'Fuerza 11, Compleja, Ver',
        '9',
        '-3',
        '20',
      ],
      [
        'Bala',
        '60',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para arcabuces',
        '11',
        '5',
        '15',
      ],
      [
        'Piedras de honda',
        '15',
        '',
        '',
        'CON',
        '',
        'Munición',
        'Munición para honda',
        '7',
        '2',
        '10',
      ],
    ],
  },
  {
    name: 'Armas de asedio',
    header: [
      'ARMA',
      'Daño',
      'Turno',
      'FUE R.',
      'Critico 1',
      'Critico 2',
      'Tipo de arma',
      'Especial',
      'Enderz.',
      'Rot',
      'Pres.',
    ],
    body: [
      [
        'Balista ligera',
        '',
        '-80',
        'NA',
        '',
        '',
        'Proyectil',
        'Fuerza 12, Ver',
        '18',
        '-',
        '25',
      ],
      [
        'Virote ligero',
        '120',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para balistas ligeras',
        '16',
        '8',
        '15',
      ],
      [
        'Balista pesada',
        '',
        '-100',
        'NA',
        '',
        '',
        'Proyectil',
        'Fuerza 13, Ver',
        '20',
        '-',
        '30',
      ],
      [
        'Virote pesado',
        '150',
        '',
        '',
        'PEN',
        '',
        'Munición',
        'Munición para balistas pesadas',
        '18',
        '12',
        '15',
      ],
      [
        'Cañón',
        '',
        '-100',
        'NA',
        '',
        '',
        'Proyectil',
        'Fuerza 14, Ver',
        '24',
        '-',
        '30',
      ],
      [
        'Bala de cañón',
        '150',
        '',
        '',
        'CON',
        '',
        'Munición',
        'Munición para cañones',
        '20',
        '14',
        '15',
      ],
    ],
  },
  {
    name: 'Armaduras',
    header: [
      'Nombre',
      'Requerimiento de armadura',
      'Penalizador natural',
      'Restricción al movimiento',
      'Endereza',
      'Presen.',
      'Localización',
      'Clase',
    ],
    body: [
      [
        'Acolchada',
        '0',
        '-5',
        '0',
        '10',
        '25',
        'Camisola',
        'Blanda',
      ],
      [
        'Cota de cuero',
        '0',
        '0',
        '0',
        '12',
        '25',
        'Camisola',
        'Blanda',
      ],
      [
        'Gabardina',
        '0',
        '-5',
        '0',
        '10',
        '25',
        'Completa',
        'Blanda',
      ],
      [
        'Piel',
        '10',
        '-10',
        '0',
        '10',
        '25',
        'Camisola',
        'Blanda',
      ],
      [
        'Completa de cuero',
        '10',
        '0',
        '1',
        '12',
        '25',
        'Completa',
        'Blanda',
      ],
      [
        'Cuero endurecido',
        '20',
        '-10',
        '0',
        '13',
        '25',
        'Peto',
        'Dura',
      ],
      [
        'Cuero tachonado',
        '25',
        '-10',
        '1',
        '14',
        '25',
        'Peto',
        'Dura',
      ],
      [
        'Mallas',
        '30',
        '-15',
        '1',
        '15',
        '30',
        'Completa',
        'Blanda',
      ],
      [
        'Peto',
        '40',
        '-15',
        '1',
        '16',
        '30',
        'Peto',
        'Dura',
      ],
      [
        'Piezas',
        '50',
        '-20',
        '2',
        '15',
        '30',
        'Completa',
        'Dura',
      ],
      [
        'Anillas',
        '60',
        '-20',
        '2',
        '15',
        '30',
        'Camisola',
        'Blanda',
      ],
      [
        'Semicompleta',
        '70',
        '-20',
        '3',
        '16',
        '35',
        'Completa',
        'Dura',
      ],
      [
        'Escamas',
        '80',
        '-25',
        '3',
        '17',
        '35',
        'Completa',
        'Dura',
      ],
      [
        'Placas',
        '90',
        '-35',
        '4',
        '17',
        '40',
        'Completa',
        'Dura',
      ],
      [
        'Completa',
        '100',
        '-50',
        '4',
        '18',
        '45',
        'Completa',
        'Dura',
      ],
      [
        'Completa dura',
        '120',
        '-60',
        '5',
        '19',
        '45',
        'Completa',
        'Dura',
      ],
      [
        'De campaña pesada',
        '150',
        '-70',
        '6',
        '20',
        '50',
        'Completa',
        'Dura',
      ],
    ],
  },
  {
    name: 'Tipos de armaduras',
    header: [
      'Nombre',
      'FIL',
      'CON',
      'PEN',
      'CAL',
      'ELE',
      'FRI',
      'ENE',
    ],
    body: [
      [
        'Acolchada',
        '1',
        '1',
        '1',
        '1',
        '2',
        '2',
        '0',
      ],
      [
        'Cuero',
        '1',
        '0',
        '2',
        '1',
        '2',
        '1',
        '0',
      ],
      [
        'Gabardina armada',
        '1',
        '0',
        '2',
        '1',
        '2',
        '2',
        '0',
      ],
      ['Piel', '2', '1', '2', '1', '2', '2', '0'],
      [
        'Completa de cuero',
        '1',
        '0',
        '2',
        '1',
        '2',
        '1',
        '0',
      ],
      [
        'Cuero endurecido',
        '2',
        '2',
        '2',
        '2',
        '2',
        '2',
        '0',
      ],
      [
        'Cuero tachonado',
        '3',
        '1',
        '2',
        '2',
        '1',
        '2',
        '0',
      ],
      [
        'Mallas',
        '4',
        '2',
        '1',
        '2',
        '0',
        '1',
        '0',
      ],
      ['Peto', '4', '5', '4', '1', '0', '1', '0'],
      [
        'Piezas',
        '4',
        '3',
        '2',
        '3',
        '2',
        '2',
        '0',
      ],
      [
        'Anillas',
        '4',
        '3',
        '1',
        '2',
        '0',
        '1',
        '0',
      ],
      [
        'Semicompleta',
        '4',
        '4',
        '4',
        '2',
        '0',
        '1',
        '1',
      ],
      [
        'Escamas',
        '4',
        '4',
        '4',
        '3',
        '0',
        '3',
        '1',
      ],
      [
        'Placas',
        '5',
        '4',
        '5',
        '3',
        '0',
        '3',
        '1',
      ],
      [
        'Completa',
        '5',
        '5',
        '5',
        '4',
        '0',
        '4',
        '2',
      ],
      [
        'Completa pesada',
        '6',
        '6',
        '6',
        '4',
        '0',
        '4',
        '2',
      ],
      [
        'De campaña pesada',
        '7',
        '7',
        '7',
        '4',
        '0',
        '4',
        '2',
      ],
    ],
  },
  {
    name: 'Yelmos',
    header: [
      'Nombre',
      'Requerimiento de armadura',
      'Penalizador a la percepción',
      'Endereza',
      'Presen.',
      'Localización',
      'Tipo',
    ],
    body: [
      [
        'Anilla',
        '0',
        '0',
        '8',
        '15',
        'Cabeza',
        'Dura',
      ],
      [
        'Frentón',
        '0',
        '0',
        '12',
        '15',
        'Cabeza',
        'Dura',
      ],
      [
        'Coronilla',
        '0',
        '0',
        '12',
        '15',
        'Cabeza',
        'Dura',
      ],
      [
        'Capucha de cuero',
        '0',
        '0',
        '10',
        '15',
        'Cabeza',
        'Blanda',
      ],
      [
        'Capucha de maya',
        '0',
        '-10',
        '13',
        '20',
        'Cabeza',
        'Blanda',
      ],
      [
        'Completo abierto',
        '5',
        '-20',
        '16',
        '25',
        'Cabeza',
        'Dura',
      ],
      [
        'Completo cerrado',
        '10',
        '-30',
        '16',
        '25',
        'Cabeza',
        'Dura',
      ],
    ],
  },
  {
    name: 'Protección de los yelmos',
    header: [
      'Nombre',
      'FIL',
      'CON',
      'PEN',
      'CAL',
      'ELE',
      'FRI',
      'ENE',
    ],
    body: [
      [
        'Anilla',
        '2',
        '2',
        '1',
        '1',
        '1',
        '1',
        '0',
      ],
      [
        'Frentón',
        '3',
        '3',
        '3',
        '1',
        '1',
        '2',
        '0',
      ],
      [
        'Coronilla',
        '4',
        '4',
        '3',
        '2',
        '0',
        '3',
        '0',
      ],
      [
        'Capucha de cuero',
        '1',
        '0',
        '2',
        '1',
        '3',
        '1',
        '0',
      ],
      [
        'Capucha de mallas',
        '4',
        '2',
        '1',
        '2',
        '0',
        '1',
        '0',
      ],
      [
        'Completo abierto',
        '5',
        '4',
        '5',
        '3',
        '0',
        '3',
        '0',
      ],
      [
        'Completo cerrado',
        '5',
        '5',
        '5',
        '4',
        '0',
        '4',
        '2',
      ],
    ],
  },
  {
    name: 'Acciones',
    header: [
      'Destreza + Agilidad',
      'Número máximo de acciones',
    ],
    body: [
      ['1 a 10', '1'],
      ['11 a 14', '2'],
      ['15 a 19', '3'],
      ['20 a 22', '4'],
      ['23 a 25', '5'],
      ['26 a 28', '6'],
      ['29 a 31', '8'],
      ['32 o más', '10'],
    ],
  },
  {
    name: 'La tabla de daños calculados',
    header: [
      '%/daño',
      '10',
      '20',
      '30',
      '40',
      '50',
      '60',
      '70',
      '80',
      '90',
      '100',
      '+5',
    ],
    body: [
      [
        '10%',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '+0',
      ],
      [
        '20%',
        '2',
        '4',
        '6',
        '8',
        '10',
        '12',
        '14',
        '16',
        '18',
        '20',
        '+1',
      ],
      [
        '30%',
        '9',
        '6',
        '9',
        '12',
        '15',
        '18',
        '21',
        '24',
        '27',
        '30',
        '+1',
      ],
      [
        '40%',
        '4',
        '8',
        '12',
        '16',
        '20',
        '24',
        '28',
        '32',
        '36',
        '40',
        '+2',
      ],
      [
        '50%',
        '5',
        '10',
        '15',
        '20',
        '25',
        '30',
        '35',
        '40',
        '45',
        '50',
        '+2',
      ],
      [
        '60%',
        '6',
        '12',
        '18',
        '24',
        '30',
        '36',
        '42',
        '48',
        '54',
        '60',
        '+3',
      ],
      [
        '70%',
        '7',
        '14',
        '21',
        '28',
        '35',
        '42',
        '49',
        '56',
        '63',
        '70',
        '+3',
      ],
      [
        '80%',
        '8',
        '16',
        '24',
        '32',
        '40',
        '48',
        '56',
        '64',
        '72',
        '80',
        '+4',
      ],
      [
        '90%',
        '9',
        '18',
        '27',
        '36',
        '45',
        '54',
        '63',
        '72',
        '81',
        '90',
        '+4',
      ],
      [
        '100%',
        '10',
        '20',
        '30',
        '40',
        '50',
        '60',
        '70',
        '80',
        '90',
        '100',
        '+5',
      ],
      [
        '110%',
        '11',
        '22',
        '33',
        '44',
        '55',
        '66',
        '77',
        '88',
        '99',
        '110',
        '+5',
      ],
      [
        '120%',
        '12',
        '24',
        '36',
        '48',
        '60',
        '72',
        '84',
        '96',
        '108',
        '120',
        '+6',
      ],
      [
        '130%',
        '13',
        '26',
        '39',
        '52',
        '65',
        '78',
        '91',
        '104',
        '117',
        '130',
        '+6',
      ],
      [
        '140%',
        '14',
        '28',
        '42',
        '56',
        '70',
        '84',
        '98',
        '112',
        '126',
        '140',
        '+7',
      ],
      [
        '150%',
        '15',
        '30',
        '45',
        '60',
        '75',
        '90',
        '105',
        '120',
        '135',
        '150',
        '+7',
      ],
      [
        '160%',
        '16',
        '32',
        '48',
        '64',
        '80',
        '96',
        '112',
        '128',
        '144',
        '160',
        '+8',
      ],
      [
        '170%',
        '17',
        '34',
        '51',
        '68',
        '85',
        '102',
        '119',
        '136',
        '153',
        '170',
        '+8',
      ],
      [
        '180%',
        '18',
        '36',
        '54',
        '72',
        '90',
        '108',
        '126',
        '144',
        '162',
        '180',
        '+9',
      ],
      [
        '190%',
        '19',
        '38',
        '57',
        '76',
        '95',
        '114',
        '133',
        '152',
        '171',
        '190',
        '+9',
      ],
      [
        '200%',
        '20',
        '40',
        '60',
        '80',
        '100',
        '120',
        '140',
        '160',
        '180',
        '200',
        '+10',
      ],
    ],
  },
  {
    name: 'Situaciones especiales de combate',
    header: [
      'Situación',
      'Ataque',
      'Parada',
      'Esquiva',
      'Turno',
      'Acción Física',
    ],
    body: [
      ['Flanco', '-10', '-30', '-30', '-', '-'],
      ['Espalda', '-30', '-80', '-80', '-', '-'],
      [
        'Sorpresa',
        'NA',
        '-90',
        '-90',
        'NA',
        '-90',
      ],
      [
        'Ceguera parcial',
        '-30',
        '-30',
        '-15',
        '-',
        '-',
      ],
      [
        'Ceguera absoluta',
        '-100',
        '-80',
        '-80',
        '-',
        '-',
      ],
      [
        'Posición superior',
        '-20',
        '-',
        '-',
        '-',
        '-',
      ],
      [
        'Derribado',
        '-30',
        '-30',
        '-30',
        '-10',
        '-30',
      ],
      [
        'Parálisis menor',
        '-20',
        '-20',
        '-40',
        '-20',
        '-40',
      ],
      [
        'Parálisis parcial',
        '-80',
        '-80',
        '-80',
        '-30',
        '-60',
      ],
      [
        'Parálisis completa',
        '-200',
        '-200',
        '-200',
        '-100',
        '-200',
      ],
      [
        'Amenazado',
        '-20',
        '-120',
        '-120',
        '-50',
        '-100',
      ],
      [
        'Levitando',
        '-20',
        '-20',
        '-40',
        '-',
        '-60',
      ],
      [
        'Vuelo tipo 7 a 14',
        '+10',
        '+10',
        '+10',
        '+10',
        '-',
      ],
      [
        'Vuelo 15 o superior',
        '+15',
        '+10',
        '+20',
        '+10',
        '-',
      ],
      ['Cargando', '+10', '+10', '+20', '-', '-'],
      [
        'Desenfundar',
        '-25',
        '-25',
        '-',
        '-',
        '-25',
      ],
      [
        'Espacio reducido',
        '-40 esp',
        '-40 esp',
        '-40',
        '-',
        '-20',
      ],
      [
        'Adversario pequeño',
        '-10',
        '-',
        '-',
        '-',
        '-',
      ],
      [
        'Adversario diminuto',
        '-20',
        '-10',
        '-',
        '-',
        '-',
      ],
    ],
  },
  {
    name: 'Defensa adicional',
    header: [
      'Ataque número',
      'Penalizador defensivo',
    ],
    body: [
      ['2°', '-30'],
      ['3°', '-50'],
      ['4°', '-70'],
      ['5°+', '-90'],
    ],
  },
  {
    name: 'Ataques apuntados',
    header: [
      'Área del cuerpo',
      'Penalizador contra humanos',
    ],
    body: [
      ['Cuello', '-80'],
      ['Cabeza', '-60'],
      ['Codo', '-60'],
      ['Corazón', '-60'],
      ['Ingle', '-60'],
      ['Pie', '-50'],
      ['Mano', '-40'],
      ['Rodilla', '-40'],
      ['Abdomen', '-20'],
      ['Brazo', '-20'],
      ['Muslo', '-20'],
      ['Pantorrilla', '-10'],
      ['Torso', '-10'],
      ['Ojo', '-100'],
      ['Muñeca', '-40'],
      ['Hombro', '-30'],
    ],
  },
  {
    name: 'Alcance por fuerza',
    header: [
      'Fuerza',
      'Distancia',
      'Calidad del arma',
    ],
    body: [
      ['3', '-30 metros', ''],
      ['4', '-10 metros', ''],
      ['5/6', 'Ninguno', ''],
      ['7', '+10 metros', ''],
      ['8', '+20 metros', ''],
      ['9', '+30 metros', ''],
      ['10', '+50 metros', ''],
      ['11', '+100 metros', '+5'],
      ['12', '+250 metros', '+10'],
      ['13', '+500 metros', '+10'],
      ['14', '+1 kilómetro', '+15'],
      ['15', '+5 kilómetros', '+15'],
      ['16+', '+10 kilómetros', '+20'],
    ],
  },
  {
    name: 'Modificadores a los proyectiles',
    header: ['Situación', 'Modificadores'],
    body: [
      [
        'Desplazarse a más de una cuarta parte del Tipo de movimiento',
        '-10',
      ],
      [
        'Correr al máximo del Tipo de movimiento',
        '-50',
      ],
      ['Escasa visibilidad', '-20'],
      ['El blanco tiene cobertura', '-40'],
      ['Cambiar de blanco', '-10'],
      [
        'Si el blanco se mueve a más de velocidad 8',
        '-20',
      ],
      [
        'Si el blanco se mueve a velocidad 10',
        '-40',
      ],
      [
        'Si el blanco se mueve a una velocidad superior a 10',
        '-60',
      ],
      [
        'Por haber defendido el mismo asalto',
        '-40',
      ],
      [
        'Atacar por encima del alcance efectivo del arma',
        '-30',
      ],
      ['Blanco grande', '+30'],
      ['Apuntar un turno', '+10'],
      ['Apuntar dos turnos', '+20'],
      ['Apuntar tres turnos', '+30'],
      ['Por disparo a bocajarro', '+30'],
    ],
  },
  {
    name: 'Dificultades de disparo',
    header: ['Situación', 'Dificultad'],
    body: [
      ['A bocajarro: Menos de 1m.', 'Fácil'],
      ['Corto alcance: 2 a 10 m', 'Media'],
      ['Medio alcance: 11 a 50 m', 'Difícil'],
      [
        'Largo alcance: 51 a 150 m',
        'Muy Difícil',
      ],
      [
        'Muy largo alcance: 151 a 500 m',
        'Absurdo',
      ],
      [
        'Distancias extremas: De 500 m. a 1Km.',
        'Casi imposible',
      ],
      [
        'Inclasificable: Más de 1 km.',
        'Imposible',
      ],
    ],
  },
  {
    name: 'Defensa contra proyectiles',
    header: [
      'Situación',
      'Contra disparos',
      'Contra lanzamientos',
    ],
    body: [
      ['Parada', '-80', '-50'],
      ['Esquiva', '-30', 'NA'],
      ['Parada con maestría', '-20', 'NA'],
      ['Esquiva con maestría', 'NA', 'NA'],
      ['Parada con un escudo', '-30', 'NA'],
      [
        'Parada con maestría y escudo',
        'NA',
        'NA',
      ],
    ],
  },
  {
    name: 'Críticos en combate',
    header: [
      'Nivel de crítico',
      'Localiz.',
      'Efecto',
    ],
    body: [
      [
        '1 a 50',
        'No',
        'Se recibe un negativo a toda acción equivalente al Nivel del Critico. El penalizador se recupera a un ritmo de 5 puntos por asalto.',
      ],
      [
        '51 a 100',
        'Si',
        'Se recibe un negativo a toda acción equivalente al Nivel de Critico. El penalizador se recupera a un ritmo de 5 puntos por asalto hasta la mitad de su valor. Hay que localizar el punto donde se sufre el impacto.',
      ],
      [
        '101 a 150',
        'Si',
        'Se recibe un negativo a toda acción equivalente al Nivel de Critico. El penalizador se recupera a un ritmo de 5 puntos por asalto hasta la mitad de su valor. Si la localización indica un miembro este queda destrozado o amputado de manera irrecuperable. Si alcanza la cabeza o el corazon el personaje muere.',
      ],
      [
        'Más de 150',
        'Si',
        'Igual que el anterior, sólo que el personaje queda además inconsciente automáticamente, y muere en un número de minutos equivalente a su Constitución si no recibe atención médica-',
      ],
    ],
  },
  {
    name: 'Localización general',
    header: ['Localización', 'Resultado'],
    body: [
      ['Torso', '1-50'],
      ['Costillas', '1-10'],
      ['Hombro', '11-20'],
      ['Estómago', '21-30'],
      ['Riñones', '31-35'],
      ['Pecho', '36-48'],
      ['Corazón', '49-50'],
      ['Brazo derecho', '51-60'],
      ['Antebrazo superior', '51-54'],
      ['Antebrazo inferior', '55-58'],
      ['Mano', '59-60'],
      ['Brazo izquierdo', '61-70'],
      ['Antebrazo superior', '61-64'],
      ['Antebrazo inferior', '65-68'],
      ['Mano', '69-70'],
      ['Pierna derecha', '71-80'],
      ['Muslo', '71-74'],
      ['Pantorrilla', '75-78'],
      ['Pie', '79-80'],
      ['Pierna izquierda', '81-90'],
      ['Muslo', '81-84'],
      ['Pantorrilla', '85-88'],
      ['Pie', '89-90'],
      ['Cabeza', '91-100'],
    ],
  },
  {
    name: 'La pifia en turno',
    header: ['Resultado', 'Penalizador al turno'],
    body: [
      ['01', '-125'],
      ['02', '-100'],
      ['03', '-75'],
    ],
  },
  {
    name: 'Acumulación de Ki',
    header: [
      'Característica',
      'Acumulación base',
    ],
    body: [
      ['1 a 9', '1'],
      ['10 a 12', '2'],
      ['13 a 15', '3'],
      ['+16', '4'],
    ],
  },
  {
    name: 'Los niveles de las técnicas',
    header: [
      'Nivel',
      'CM Máximo',
      'CM Mínimo',
      'Desventajas',
    ],
    body: [
      ['1', '50', '20', '1'],
      ['2', '100', '40', '2'],
      ['3', '200', '60', '3'],
    ],
  },
  {
    name: 'El zeon base',
    header: ['Poder', 'Zeon Base'],
    body: [
      ['1', '5'],
      ['2', '20'],
      ['3', '40'],
      ['4', '55'],
      ['5', '70'],
      ['6', '85'],
      ['7', '95'],
      ['8', '110'],
      ['9', '120'],
      ['10', '135'],
      ['11', '150'],
      ['12', '160'],
      ['13', '175'],
      ['14', '185'],
      ['15', '200'],
      ['16', '215'],
      ['17', '225'],
      ['18', '240'],
      ['19', '250'],
      ['20', '265'],
    ],
  },
  {
    name: 'El ACT base',
    header: ['Poder', 'ACT base'],
    body: [
      ['1 a 4', '0'],
      ['5 a 7', '5'],
      ['8 a 11', '10'],
      ['12 a 14', '15'],
      ['15', '20'],
      ['16 a 17', '25'],
      ['18 a 19', '30'],
      ['20', '35'],
    ],
  },
  {
    name: 'Choque de descargas',
    header: ['Diferencia', 'Efecto'],
    body: [
      ['1 a 50', 'Ambos se anulan.'],
      [
        '51 a 100',
        'El ganador consigue pasar a través del otro, pero su daño base queda reducido a la mitad.',
      ],
      [
        '+100',
        'El ataque inferior queda totalmente anulado y el vencedor continua su trayectoria sin ningún penalizador a su daño',
      ],
    ],
  },
  {
    name: 'Magia innata',
    header: ['ACT del hechicero', 'Zeon'],
    body: [
      ['10 a 50', 'Hasta 10 de Zeon'],
      ['55 a 70', 'Hasta 20 de Zeon'],
      ['75 a 90', 'Hasta 30 de Zeon'],
      ['95 a 110', 'Hasta 40 de Zeon'],
      ['115 a 130', 'Hasta 50 de Zeon'],
      ['135 a 150', 'Hasta 60 de Zeon'],
      ['155 a 180', 'Hasta 70 de Zeon'],
      ['185 a 200', 'Hasta 80 de Zeon'],
      ['+200', 'Hasta 90 de Zeon'],
    ],
  },
  {
    name: 'El nivel de magia',
    header: [
      'Inteligencia',
      'Nivel de magia máximo',
    ],
    body: [
      ['1 a 5', '0'],
      ['6', '10'],
      ['7', '20'],
      ['8', '30'],
      ['9', '40'],
      ['10', '50'],
      ['11', '75'],
      ['12', '100'],
      ['13', '150'],
      ['14', '200'],
      ['15', '300'],
      ['16', '400'],
      ['17', '500'],
      ['18', '600'],
      ['19', '700 '],
      ['20', '800'],
    ],
  },
  {
    name: 'Selección de conjuros',
    header: [
      'Nivel del conjuro',
      'Coste en nivel de magia',
    ],
    body: [
      ['2 a 10', '2'],
      ['12 a 20', '4'],
      ['22 a 30', '6'],
      ['32 a 40', '8'],
      ['42 a 50', '10'],
      ['52 a 60', '12'],
      ['62 a 70', '14'],
      ['72 a 80', '16'],
      ['82 a 90', '18'],
      ['92 a 100', '20'],
    ],
  },
  {
    name: 'Rituales mágicos',
    header: [
      'Preparatoria',
      'Bono a INT',
      'Coste adicional',
    ],
    body: [
      ['Una hora', '+1', '+50%'],
      ['Un día entero', '+2', 'Doble'],
      ['Tres dias', '+3', 'Triple'],
      ['Una semana', '+4', 'Cuádruple'],
      ['Un año', '+5', 'Quíntuple'],
    ],
  },
  {
    name: 'Modificadores a la detección mágica',
    header: ['Situación', 'Modificador'],
    body: [
      [
        'La fuente mágica está a más de 20 metros',
        '-20',
      ],
      [
        'La fuente mágica está a más de 50 metros',
        '-40',
      ],
      [
        'La fuente mágica está a más de 100 metros',
        '-80',
      ],
      [
        'La fuente mágica está a más de 1 Kilómetro',
        '-120',
      ],
      [
        'Ambiente ligeramente cargado de magia*',
        '-40',
      ],
      [
        'Ambiente fuertemente cargado de magia*',
        '-80',
      ],
    ],
  },
  {
    name: 'Análisis mágico',
    header: ['Nivel del conjuro', 'Efecto'],
    body: [
      [
        'Fácil',
        'Reconocer la naturaleza de la magia',
      ],
      ['Media', 'Nivel de magia 20'],
      ['Difícil', 'Nivel de magia 40'],
      ['Muy difícil', 'Nivel de magia 60'],
      ['Absurdo', 'Nivel de magia 70'],
      ['Casi Imposible', 'Nivel de magia 80'],
      ['Imposible', 'Nivel de magia 90'],
      ['Inhumano', 'Nivel de magia 100'],
    ],
  },
  {
    name: 'Las dificultades de convocación',
    header: [
      'Nivel',
      'Invocar',
      'Zeon',
      'Controlar',
      'Zeon',
      'Atar',
      'Zeon',
      'Desconvocar',
      'Zeon',
    ],
    body: [
      [
        '0',
        '140',
        '10',
        '180',
        '20',
        '160',
        '5',
        '100',
        '5',
      ],
      [
        '1',
        '160',
        '20',
        '200',
        '40',
        '180',
        '10',
        '120',
        '5',
      ],
      [
        '2',
        '180',
        '40',
        '220',
        '80',
        '200',
        '30',
        '160',
        '10',
      ],
      [
        '3',
        '200',
        '60',
        '240',
        '120',
        '220',
        '30',
        '160',
        '15',
      ],
      [
        '4',
        '220',
        '80',
        '260',
        '160',
        '240',
        '40',
        '180',
        '20',
      ],
      [
        '5',
        '240',
        '100',
        '280',
        '200',
        '260',
        '50',
        '200',
        '25',
      ],
      [
        '6',
        '260',
        '120',
        '300',
        '240',
        '280',
        '60',
        '220',
        '30',
      ],
      [
        '7',
        '280',
        '140',
        '320',
        '280',
        '300',
        '70',
        '240',
        '40',
      ],
      [
        '8',
        '300',
        '160',
        '340',
        '320',
        '320',
        '80',
        '260',
        '50',
      ],
      [
        '9',
        '320',
        '180',
        '360',
        '360',
        '340',
        '90',
        '280',
        '60',
      ],
      [
        '10',
        '340',
        '200',
        '380',
        '400',
        '360',
        '100',
        '300',
        '80',
      ],
      [
        '11',
        '360',
        '220',
        '400',
        '440',
        '380',
        '120',
        '320',
        '100',
      ],
      [
        '12',
        '380',
        '240',
        '420',
        '480',
        '400',
        '140',
        '340',
        '120',
      ],
      [
        '13',
        '400',
        '260',
        '440',
        '520',
        '420',
        '160',
        '360',
        '140',
      ],
      [
        '14',
        '420',
        '280',
        '460',
        '560',
        '440',
        '180',
        '380',
        '160',
      ],
      [
        '15',
        '440',
        '300',
        '480',
        '600',
        '460',
        '200',
        '400',
        '180',
      ],
    ],
  },
  {
    name: 'El tiempo de los rituales',
    header: [
      'Tiempo utilizado en la invocación',
      'Bonos utilizables',
    ],
    body: [
      ['Inmediato', '-100'],
      ['Un asalto completo', '-50'],
      ['Tres asaltos', '-20'],
      ['Cinco asaltos', '+0'],
      ['Un minuto', '+10'],
      ['Una hora', '+20'],
      ['Seis horas', '+30'],
      ['Un día', '+40'],
      ['Una semana', '+50'],
      ['Un mes', '+60'],
      ['Seis meses', '+70'],
      ['Un año', '+80'],
      ['Cinco años', '+90'],
      ['Diez años', '+100'],
      ['Más de cincuenta años', '+120'],
    ],
  },
  {
    name: 'Modificadores de la convocatoria',
    header: [
      'Modificadores de convocatoria',
      'Bonos utilizables',
    ],
    body: [
      ['Conocer el nombre del ser', '+20'],
      ['Tener una pertenencia suya', '+10'],
      ['Tener una parte de él', '+20'],
      ['No conocer el tipo de criatura', '-50'],
    ],
  },
  {
    name: 'La rueda',
    header: ['Resultado', 'Invocación'],
    body: [
      ['1 a 5', 'El loco'],
      ['5 a 10', 'El Hierofante'],
      ['11 a 15', 'La suma sacerdotisa'],
      ['16 a 20', 'La Emperatriz'],
      ['21 a 25', 'El Emperador'],
      ['26 a 30', 'El Sumo Sacerdote'],
      ['31 a 35', 'Los Enamorados'],
      ['36 a 40', 'El Carro'],
      ['41 a 45', 'La Fuerza'],
      ['46 a 50', 'El Ermitaño'],
      ['51 a 55', 'La Justicia'],
      ['56 a 60', 'El Colgado'],
      ['61 a 65', 'La Muerte'],
      ['66 a 70', 'La Templanza'],
      ['71 a 75', 'El Diablo'],
      ['76 a 80', 'La Torre'],
      ['81 a 85', 'La Estrella'],
      ['86 a 90', 'La Luna'],
      ['91 a 95', 'El Sol'],
      ['96 a 99', 'El Juicio'],
      ['100', 'El Mundo'],
    ],
  },
  {
    name: 'Potencial psíquico base',
    header: ['Voluntad', 'Potencial psíquico'],
    body: [
      ['4 o menos', '+0'],
      ['5', '+10'],
      ['6', '+20'],
      ['7', '+30'],
      ['8', '+40'],
      ['9', '+50'],
      ['10', '+60'],
      ['11', '+70'],
      ['12', '+80'],
      ['13', '+90'],
      ['14', '+100'],
      ['15', '+120'],
      ['16', '+140'],
      ['17', '+160'],
      ['18', '+180'],
      ['19', '+200'],
      ['20', '+220'],
    ],
  },
  {
    name: 'La concentración',
    header: [
      'Concentración',
      'Bonos utilizables',
    ],
    body: [
      ['Un asalto', '+10'],
      ['Tres asaltos', '+20'],
      ['Cinco asaltos', '+30'],
      ['Un minuto', '+40'],
      ['Una hora', '+50'],
    ],
  },
  {
    name: 'Incrementar el potencial psíquico',
    header: [
      'CV necesarios',
      'Potencial psíquico',
    ],
    body: [
      ['1 (1)', '+10'],
      ['2 (3)', '+20'],
      ['3 (6)', '+30'],
      ['4 (10)', '+40'],
      ['5 (15)', '+50'],
      ['6 (21)', '+60'],
      ['7 (28)', '+70'],
      ['8 (36)', '+80'],
      ['9 (45)', '+90'],
      ['10 (55)', '+100'],
    ],
  },
  {
    name: 'Caídas',
    header: [
      'Distancia',
      'Dificultad',
      'Daño base',
    ],
    body: [
      ['2 Metros', 'Fácil', '20'],
      ['5 Metros', 'Media', '40'],
      ['10 Metros', 'Difícil', '60'],
      ['15 Metros', 'Muy difícil', '80'],
      ['20 Metros', 'Absurdo', '100'],
      ['30 Metros', 'Casi imposible', '120'],
      ['50 Metros', 'Imposible', '140'],
      ['+50 Metros', 'Inhumano', '160'],
    ],
  },
  {
    name: 'Trampas',
    header: ['Nivel', 'Dificultad'],
    body: [
      ['10', 'Rutinaria'],
      ['20', 'Fácil'],
      ['30', 'Media'],
      ['40', 'Difícil'],
      ['50', 'Muy difícil'],
      ['60', 'Absurdo'],
      ['70', 'Casi imposible'],
      ['80', 'Imposible'],
      ['90', 'Inhumano'],
      ['100', 'Zen'],
    ],
  },
  {
    name: 'Niveles de veneno',
    header: ['Nivel', 'Resistencia'],
    body: [
      ['10', 'La RV es contra 20'],
      ['20', 'La RV es contra 40'],
      ['30', 'La RV es contra 60'],
      ['40', 'La RV es contra 80'],
      ['50', 'La RV es contra 100'],
      ['60', 'La RV es contra 120'],
      ['70', 'La RV es contra 140'],
      ['80', 'La RV es contra 160'],
      ['90', 'La RV es contra 180'],
      ['100', 'La RV es contra 200'],
    ],
  },
  {
    name: 'Venenos',
    header: [
      'Nombre',
      'Nivel',
      'Efectos/RV',
      'Activación',
      'Duración',
      'Afección',
    ],
    body: [
      [
        'Curare',
        '60',
        'Paralización RV 80, Muerte RV 60',
        'Rápida',
        'Normal',
        'Por sangre',
      ],
      [
        'Atropina',
        '50',
        'Alucinaciones RV 80',
        'Normal',
        'Normal',
        'Por contacto',
      ],
      [
        'Vinagre de saturno',
        '40',
        'Dolor RV 60, Ceguera RV 40',
        'Normal',
        'Larga',
        'Ingestion',
      ],
      [
        'Muscarina',
        '40',
        'Alucinaciones RV 60',
        'Normal',
        'Normal',
        'Por via olfativa',
      ],
      [
        'Arsénico real',
        '50',
        'Muerte RV 80',
        'Normal',
        'Normal',
        'Ingestión',
      ],
      [
        'Belladona',
        '50',
        'Inconsciencia RV 80',
        'Rápida',
        'Larga',
        'Ingestión',
      ],
      [
        'Cianuro',
        '50',
        'Muerte RV 60',
        'Instantánea',
        'Normal',
        'Ingestion',
      ],
      [
        'Cantaridina',
        '30',
        'Ira RV 60',
        'Normal',
        'Normal',
        'Por sangre',
      ],
      [
        'Talio',
        '20',
        'Dolor RV 40',
        'Normal',
        'Normal',
        'Por sangre',
      ],
      [
        'Acqua Toffana',
        '40',
        'Debilidad RV 80, Negativo a toda acción RV 60',
        'Retardada',
        'Larga',
        'Ingestion',
      ],
      [
        'Al-Baladín',
        '60',
        'Daño RV 100, Negativo a toda acción RV 80',
        'Rápida',
        'Normal',
        'Por sangre',
      ],
      [
        'Savia de Ramalen',
        '80',
        'Terror RV 120, Ceguera RV 100',
        'Rápida',
        'Normal',
        'Por contacto',
      ],
      [
        'De serpiente',
        '40',
        'Muerte RV 60',
        'Normal',
        'Normal',
        'Por sangre',
      ],
      [
        'Cobra blanca',
        '70',
        'Muerte RV 100',
        'Instantánea',
        'Normal',
        'Por sangre',
      ],
    ],
  },
  {
    name: 'Enfermedades',
    header: ['Nivel', 'Resistencia'],
    body: [
      ['10', 'La RE es contra 20'],
      ['20', 'La RE es contra 40'],
      ['30', 'La RE es contra 60'],
      ['40', 'La RE es contra 80'],
      ['50', 'La RE es contra 100'],
      ['60', 'La RE es contra 120'],
      ['70', 'La RE es contra 140'],
      ['80', 'La RE es contra 160'],
      ['90', 'La RE es contra 180'],
      ['100', 'La RE es contra 200'],
    ],
  },
  {
    name: 'En llamas',
    header: ['Cantidad', 'Estado'],
    body: [
      ['100 a 179', 'Prendido'],
      ['180 a 239', 'Ardiendo'],
      ['240 a 299', 'En llamas'],
      ['+300', 'Calcinado'],
    ],
  },
  {
    name: 'Intensidades de fuego',
    header: [
      'Intensidades',
      'Equivalencia',
      'Daño base',
    ],
    body: [
      ['1', 'La llama de una vela', '5'],
      ['3', 'El fuego de una antorcha', '15'],
      ['5', 'Una pequeña hoguera', '25'],
      ['7', 'Una gran hoguera', '35'],
      ['20', 'El incendio de una casa', '100'],
      [
        '30',
        'Fuegos de unos grandes hornos',
        '150',
      ],
      ['40', 'Un castillo en llamas', '200'],
      ['50', 'Un volcán', '250'],
    ],
  },
  {
    name: 'Intensidades de frío',
    header: [
      'Intensidades',
      'Equivalencia',
      'Daño base',
    ],
    body: [
      ['1', 'Escarcha', '5'],
      ['5', 'Nieve', '25'],
      ['10', 'Hielo', '50'],
      ['20', 'Iceberg', '100'],
      ['30', 'Una tormenta polar', '150'],
      ['50', 'Una zona glacial', '250'],
    ],
  },
  {
    name: 'Intensidades de electricidad',
    header: [
      'Intensidades',
      'Equivalencia',
      'Daño base',
    ],
    body: [
      ['1', 'Una chispa', '5'],
      ['3', 'Electricidad estática', '15'],
      ['5', 'Una pequeña descarga', '25'],
      [
        '7',
        'La descarga de una anguila eléctrica',
        '35',
      ],
      ['20', 'Rayo', '100'],
      [
        '40',
        'Una potente tormenta eléctrica',
        '200',
      ],
    ],
  },
  {
    name: 'Presencias',
    header: ['Equivalencia', 'Presencia'],
    body: [
      [
        'Objetos pequeños y simples (Cucharas, vasos, sillas...)',
        '10 a 25',
      ],
      [
        'Objetos complejos naturales (Relojes, catalejos, tiendas de campaña...)',
        '25 a 60',
      ],
      [
        'Gemas, materiales inusuales y obras de arte (Platino, diamantes, grandes cuadros...)',
        '40 a 80',
      ],
      [
        'Cosas de gran tamaño (Carros, grandes estatuas, colinas...)',
        '80 a 120',
      ],
      [
        'Cosas colosales (Montañas, lagos, grandes construcciones...)',
        '120 a 180',
      ],
    ],
  },
  {
    name: 'Barrera de daño y daño estructural',
    header: [
      'Elemento',
      'Presencia Base',
      'Puntos estructurales',
      'Barrera de daño',
    ],
    body: [
      ['Piedra pequeña', '10', '40', '60'],
      ['Roca enorme', '30', '300', '100'],
      ['Mesa', '20', '60', '20'],
      ['Silla', '15', '50', '20'],
      ['Barril', '20', '70', '30'],
      ['Arcón', '20', '70', '50'],
      ['Arcón reforzado', '25', '150', '80'],
      ['Carro', '40', '300', '40'],
      ['Carruaje', '50', '350', '60'],
      ['-', '-', '-', '-'],
      ['Muro de troncos', '40', '300', '60'],
      ['Muro de piedra', '50', '400', '100'],
      [
        'Muro de piedra macizo',
        '60',
        '450',
        '120',
      ],
      ['Puente', '60', '400', '90'],
      ['Puente macizo', '80', '800', '120'],
      ['-', '-', '-', '-'],
      ['Puerta normal', '20', '100', '40'],
      ['Puerta recia', '30', '200', '80'],
      ['Puerta metálica', '40', '300', '120'],
      ['Rastrillo', '60', '500', '120'],
      ['Rejas metálicas', '40', '200', '120'],
      ['-', '-', '-', '-'],
      ['Árbol pequeño', '30', '200', '40'],
      ['Árbol grande', '60', '500', '60'],
      ['-', '-', '-', '-'],
      ['Choza', '50', '400', '50'],
      ['Casa', '70', '600', '80'],
      ['Caserón', '100', '2.000', '100'],
      ['Mansión', '120', '3.000', '100'],
      ['Palacio', '140', '4.000', '120'],
      ['Castillo', '160', '5.000', '140'],
      ['-', '-', '-', '-'],
      ['Poblado', '140', 'NA', 'NA'],
      ['Ciudad', '160', 'NA', 'NA'],
      ['Metrópolis', '200', 'NA', 'NA'],
      ['-', '-', '-', '-'],
      ['Barca', '40', '200', '40'],
      ['Velero', '80', '600', '70'],
      ['Crucero', '100', '1.000', '80'],
      ['Barco gigantesco', '120', '2.000', '80'],
    ],
  },
  {
    name: 'La Experiencia en Combate',
    header: [
      'Dificultad',
      'Experiencia',
      'Explicación',
    ],
    body: [
      [
        'Rutinario',
        'Ninguna',
        'Combates que no representan ningún tipo de reto para los personajes, ya que incluso en las situaciones más adversas y con la peor de las suertes, pueden ganar sin ninguna dificultad',
      ],
      [
        'Fácil',
        '1',
        'El personaje tiene todas las posibilidades de vencer y lo hará habitualmente con facilidad. No obstante, a diferencia  del caso anterior, aunque pequeño, existe cierto riesgo para él siempre que la suerte le sea realmente adversa.',
      ],
      [
        'Media',
        '6',
        'El combate está muy igualado para ambos bandos, pero existe ligera ventaja a favor de los personajes jugadores, ya sea por habilidad o número. Generalmente, sacando las mismas tiradas, los personajes se harán con la victoria, aunque con un poco de mala suerte pueden acabar perdiendo.',
      ],
      [
        'Difícil',
        '10',
        'SE trata de un combate ligeramente equilibrado, en el que ambos contendientes o bandos tienen exactamente las mismas posibilidades de ganar.',
      ],
      [
        'Muy difícil',
        '15',
        'El combate está también muy igualado, pero en esta ocasión existe cierto desequilibrio a favor del bando antagonista, que generalmente tiende a alzarse con la victoria. A todos los efectos, es el nivel de dificultad Medio, desde la perspectiva del bando enemigo',
      ],
      [
        'Absurdo',
        '20',
        'Enfrentamientos en lso que todo resulta realmente adverso para los personajes, puesto que son seriamente superados por el poder de sus antagonistas. Sin embargo, sigue existiendo una pequeña posibilidad de ganar, siempre que la suerte les acompañe',
      ],
      [
        'Casi imposible',
        '30',
        'Se trata de combates prácticamente perdidos de antemano, puesto que el desequilibrio entre ambos bandos es casi insondable. Simplemente tener buena suerte no permite vencer la lucha y sólo en ciertas condiciones muy especiales y con una suerte de varias tiradas afortunadas, sería posible ganar este tipo de enfrentamientos.',
      ],
      [
        'Imposible',
        '60',
        'Como su nombre lo indica, son combates que ningún personaje puede ganar, y que requieren un verdadero milagro. No obstante, no hay lugar mejor que una partida de rol para ver cómo los milagros se pueden hacer realidad...',
      ],
    ],
  },
  {
    name: 'Elan',
    header: ['Elan', 'Sincronizados', 'Límite'],
    body: [
      ['Hasta 49', 'Ilimitado', 'Elan 50'],
      ['50 a 59', '1.000', 'Elan 50'],
      ['60 a 69', '500', 'Elan 40'],
      ['70 a 79', '100', 'Elan 30'],
      ['80 a 89', '10', 'Elan 20'],
      ['90 a 99', '3', 'Elan 10'],
      ['100', '1', 'Elan 0'],
    ],
  },
  {
    name: 'Características en seres mágicos',
    header: [
      'Característica',
      'Costeen PD',
      'Gnosis',
    ],
    body: [
      ['1', '1', ''],
      ['2', '2', ''],
      ['3', '3', ''],
      ['4', '4', ''],
      ['5', '5', ''],
      ['6', '6', ''],
      ['7', '7', ''],
      ['8', '8', ''],
      ['9', '10', ''],
      ['10', '15', ''],
      ['11', '20', ''],
      ['12', '30', ''],
      ['13', '40', '5'],
      ['14', '50', '15'],
      ['15', '60', '25'],
    ],
  },
  {
    name: 'La creación de seres',
    header: [
      'Tamaño',
      '',
      'Ataque físico',
      'Arma natural',
      'Turno base',
      'Área de acción',
      'Tipo de movimiento',
      'Múltiplo de acumulación',
      'Armadura',
    ],
    body: [
      [
        'Minúsculo',
        '1 a 3',
        '5',
        '20',
        '40',
        'NA',
        '-4',
        '1',
        '1',
      ],
      [
        'Pequeño',
        '4 a 8',
        '10',
        '30',
        '30',
        'NA',
        '-2',
        '2',
        '2',
      ],
      [
        'Medio',
        '9 a 22',
        '10',
        '40',
        '20',
        'NA',
        'NA',
        '5',
        '3',
      ],
      [
        'Grande',
        '23 a 24',
        '20',
        '60',
        '10',
        'NA',
        'NA',
        '5',
        '4',
      ],
      [
        'Enorme',
        '25 a 28',
        '30',
        '100',
        '0',
        '1 metro',
        '+1',
        '10',
        '6',
      ],
      [
        'Gigantesco',
        '29 a 33',
        '40',
        '120',
        '-10',
        '5 metros',
        '+2',
        '15',
        '8',
      ],
      [
        'Colosal',
        '34+',
        '60',
        '140',
        '-20',
        '20 metros',
        '+3',
        '20',
        '10',
      ],
    ],
  },
  {
    name: 'Rotura y endereza en armas naturales',
    header: ['Tamaño', 'Ruptura', 'Endereza'],
    body: [
      ['Minúscula', '-4', '4'],
      ['Pequeña', '-2', '8'],
      ['Media', '0', '12'],
      ['Grande', '4', '16'],
      ['Enorme', '8', '20'],
      ['Gigantesca', '12', '28'],
      ['Colosal', '16', '34'],
    ],
  },
  {
    name: 'Adaptaciones de características',
    header: [
      'Característica',
      '3 a 18',
      '1 a 100',
    ],
    body: [
      ['1', '3', '5'],
      ['2', '4', '15'],
      ['3', '5', '25'],
      ['4', '7', '35'],
      ['5', '9', '45'],
      ['6', '10', '55'],
      ['7', '12', '65'],
      ['8', '14', '75'],
      ['9', '16', '85'],
      ['10', '18', '95'],
      ['11', '20', '100'],
      ['12', '22', '110'],
      ['13', '25', '125'],
      ['14', '30', '150'],
      ['15', '40', '180'],
    ],
  },
]
